//USER INPUT STATE TYPES
export const EMAIL_INPUT_CHANGE       = 'EMAIL_INPUT_CHANGE';
export const PASSWORD_INPUT_CHANGE    = 'PASSWORD_INPUT_CHANGE';
export const USERNAME_INPUT_CHANGE    = 'USERNAME_INPUT_CHANGE';
export const CONFIRM_PW_INPUT_CHANGE  = 'CONFIRM_PW_INPUT_CHANGE';
export const SECRET_CODE_INPUT_CHANGE = 'SECRET_CODE_INPUT_CHANGE';

//NAVIGATION STATE TYPES
export const RESET_ON_NAVIGATION      = 'RESET_ON_NAVIGATION';

//AUTHENTICATED TYPES
export const SIGNIN_USER_SUCCESS    = 'SIGN_USER_SUCCESS';
export const SIGNIN_USER_FAIL       = 'SIGNIN_USER_FAIL';
export const SIGNOUT_USER_SUCCESS   = 'SIGNOUT_USER_SUCCESS';
export const SIGNOUT_USER_FAIL      = 'SIGNOUT_USER_FAIL';
export const SIGNUP_USER_SUCCESS    = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAIL       = 'SIGNUP_USER_FAIL';

export const RENDER_FORMS           = 'RENDER_FORMS';
export const ADMIN_AUTHENTICATION   = 'ADMIN_AUTHENTICATION';

//POll TYPES
export const POLL_TITLE_INPUT_CHANGE = 'POLL_TITLE_INPUT_CHANGE'
export const POLL_DESCRIPTION_INPUT_CHANGE = 'POLL_DESCRIPTION_INPUT_CHANGE'

//Payment TYPES
export const CARD_NUMBER_INPUT_CHANGE = 'CARD_NUMBER_INPUT_CHANGE';
export const CVC_INPUT_CHANGE         = 'CVC_INPUT_CHANGE';
export const EXP_MONTH_INPUT_CHANGE   = 'EXP_MONTH_INPUT_CHANGE'
export const EXP_YEAR_INPUT_CHANGE    = 'EXP_YEAR_INPUT_CHANGE';


//Misc types
export const DISPATCH_MESSAGE         = 'DISPATCH_MESSAGE';
